/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ouyang_srp_SrpClient */

#ifndef _Included_com_ouyang_srp_SrpClient
#define _Included_com_ouyang_srp_SrpClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    createInstance
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_srp_SrpClient_createInstance
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    releaseInstance
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_srp_SrpClient_releaseInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    set_s
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ouyang_srp_SrpClient_set_1s
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    generate_A
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ouyang_srp_SrpClient_generate_1A
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    compute_u
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ouyang_srp_SrpClient_compute_1u
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    compute_S
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ouyang_srp_SrpClient_compute_1S
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    compute_K
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ouyang_srp_SrpClient_compute_1K
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ouyang_srp_SrpClient
 * Method:    compute_M1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ouyang_srp_SrpClient_compute_1M1
    (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
